version: '3.6'

networks:
  medidor-enerbit:
    driver: bridge

services:
  medidor_enerbit:
    build: .
    restart: always
    ports:
     - "5000:5000"
     - "50001:50001"
    networks:
      - medidor-enerbit
    depends_on:
      - "db"
    volumes:
      - "./wait-for-it.sh:/wait-for-it.sh:ro"
    command: ["./wait-for-it.sh", "db:5432", "--", "./medidor-enerbit"]
    environment: # Example ENV configuration
      APP_NAME: "medidor-enerbit"
      GIN_MODE: "release"
      GIN_HTTPS: "false"
      GIN_ADDR: "0.0.0.0"
      GIN_PORT: "5000"
      LOG_LEVEL: "INFO"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "example"
      POSTGRES_DB: "postgres"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_SSL: "disable"
      POSTGRES_TIMEZONE: "Asia/Kolkata"
  db:
    image: postgres
    restart: always
    networks:
      - medidor-enerbit
    environment:
      POSTGRES_PASSWORD: example
    ports:
       - 5432:5432 # Expose this port while running REST service locally
  adminer:
    image: adminer
    networks:
      - medidor-enerbit
    restart: always
    ports:
      - 8080:8080
