// Code generated by protoc-gen-go. DO NOT EDIT.
// source: medidorgRPC.proto

package medidorgRPC

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Medidor struct {
	Brand                string               `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Address              string               `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	InstallationDate     *timestamp.Timestamp `protobuf:"bytes,3,opt,name=installationDate,proto3" json:"installationDate,omitempty"`
	RetirementDate       *timestamp.Timestamp `protobuf:"bytes,4,opt,name=retirementDate,proto3" json:"retirementDate,omitempty"`
	Serial               string               `protobuf:"bytes,5,opt,name=serial,proto3" json:"serial,omitempty"`
	Lines                uint64               `protobuf:"varint,6,opt,name=lines,proto3" json:"lines,omitempty"`
	IsActive             bool                 `protobuf:"varint,7,opt,name=isActive,proto3" json:"isActive,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Medidor) Reset()         { *m = Medidor{} }
func (m *Medidor) String() string { return proto.CompactTextString(m) }
func (*Medidor) ProtoMessage()    {}
func (*Medidor) Descriptor() ([]byte, []int) {
	return fileDescriptor_59fab903af14928d, []int{0}
}

func (m *Medidor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Medidor.Unmarshal(m, b)
}
func (m *Medidor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Medidor.Marshal(b, m, deterministic)
}
func (m *Medidor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Medidor.Merge(m, src)
}
func (m *Medidor) XXX_Size() int {
	return xxx_messageInfo_Medidor.Size(m)
}
func (m *Medidor) XXX_DiscardUnknown() {
	xxx_messageInfo_Medidor.DiscardUnknown(m)
}

var xxx_messageInfo_Medidor proto.InternalMessageInfo

func (m *Medidor) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *Medidor) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Medidor) GetInstallationDate() *timestamp.Timestamp {
	if m != nil {
		return m.InstallationDate
	}
	return nil
}

func (m *Medidor) GetRetirementDate() *timestamp.Timestamp {
	if m != nil {
		return m.RetirementDate
	}
	return nil
}

func (m *Medidor) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *Medidor) GetLines() uint64 {
	if m != nil {
		return m.Lines
	}
	return 0
}

func (m *Medidor) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type MedidorGet struct {
	Brand                string   `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Installationdate     string   `protobuf:"bytes,3,opt,name=installationdate,proto3" json:"installationdate,omitempty"`
	Retirementdate       string   `protobuf:"bytes,4,opt,name=retirementdate,proto3" json:"retirementdate,omitempty"`
	Serial               string   `protobuf:"bytes,5,opt,name=serial,proto3" json:"serial,omitempty"`
	Lines                int32    `protobuf:"varint,6,opt,name=lines,proto3" json:"lines,omitempty"`
	Isactive             bool     `protobuf:"varint,7,opt,name=isactive,proto3" json:"isactive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MedidorGet) Reset()         { *m = MedidorGet{} }
func (m *MedidorGet) String() string { return proto.CompactTextString(m) }
func (*MedidorGet) ProtoMessage()    {}
func (*MedidorGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_59fab903af14928d, []int{1}
}

func (m *MedidorGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MedidorGet.Unmarshal(m, b)
}
func (m *MedidorGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MedidorGet.Marshal(b, m, deterministic)
}
func (m *MedidorGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MedidorGet.Merge(m, src)
}
func (m *MedidorGet) XXX_Size() int {
	return xxx_messageInfo_MedidorGet.Size(m)
}
func (m *MedidorGet) XXX_DiscardUnknown() {
	xxx_messageInfo_MedidorGet.DiscardUnknown(m)
}

var xxx_messageInfo_MedidorGet proto.InternalMessageInfo

func (m *MedidorGet) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *MedidorGet) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MedidorGet) GetInstallationdate() string {
	if m != nil {
		return m.Installationdate
	}
	return ""
}

func (m *MedidorGet) GetRetirementdate() string {
	if m != nil {
		return m.Retirementdate
	}
	return ""
}

func (m *MedidorGet) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *MedidorGet) GetLines() int32 {
	if m != nil {
		return m.Lines
	}
	return 0
}

func (m *MedidorGet) GetIsactive() bool {
	if m != nil {
		return m.Isactive
	}
	return false
}

type MedidorUpdate struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address              string               `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	RetirementDate       *timestamp.Timestamp `protobuf:"bytes,3,opt,name=retirementDate,proto3" json:"retirementDate,omitempty"`
	Lines                int32                `protobuf:"varint,4,opt,name=lines,proto3" json:"lines,omitempty"`
	IsActive             bool                 `protobuf:"varint,5,opt,name=isActive,proto3" json:"isActive,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MedidorUpdate) Reset()         { *m = MedidorUpdate{} }
func (m *MedidorUpdate) String() string { return proto.CompactTextString(m) }
func (*MedidorUpdate) ProtoMessage()    {}
func (*MedidorUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_59fab903af14928d, []int{2}
}

func (m *MedidorUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MedidorUpdate.Unmarshal(m, b)
}
func (m *MedidorUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MedidorUpdate.Marshal(b, m, deterministic)
}
func (m *MedidorUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MedidorUpdate.Merge(m, src)
}
func (m *MedidorUpdate) XXX_Size() int {
	return xxx_messageInfo_MedidorUpdate.Size(m)
}
func (m *MedidorUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_MedidorUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_MedidorUpdate proto.InternalMessageInfo

func (m *MedidorUpdate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MedidorUpdate) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MedidorUpdate) GetRetirementDate() *timestamp.Timestamp {
	if m != nil {
		return m.RetirementDate
	}
	return nil
}

func (m *MedidorUpdate) GetLines() int32 {
	if m != nil {
		return m.Lines
	}
	return 0
}

func (m *MedidorUpdate) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type MedidorIsActive struct {
	IsActive             bool     `protobuf:"varint,1,opt,name=isActive,proto3" json:"isActive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MedidorIsActive) Reset()         { *m = MedidorIsActive{} }
func (m *MedidorIsActive) String() string { return proto.CompactTextString(m) }
func (*MedidorIsActive) ProtoMessage()    {}
func (*MedidorIsActive) Descriptor() ([]byte, []int) {
	return fileDescriptor_59fab903af14928d, []int{3}
}

func (m *MedidorIsActive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MedidorIsActive.Unmarshal(m, b)
}
func (m *MedidorIsActive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MedidorIsActive.Marshal(b, m, deterministic)
}
func (m *MedidorIsActive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MedidorIsActive.Merge(m, src)
}
func (m *MedidorIsActive) XXX_Size() int {
	return xxx_messageInfo_MedidorIsActive.Size(m)
}
func (m *MedidorIsActive) XXX_DiscardUnknown() {
	xxx_messageInfo_MedidorIsActive.DiscardUnknown(m)
}

var xxx_messageInfo_MedidorIsActive proto.InternalMessageInfo

func (m *MedidorIsActive) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type MedidorIsActiveResponse struct {
	Medidores            []*MedidorGet `protobuf:"bytes,1,rep,name=Medidores,proto3" json:"Medidores,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MedidorIsActiveResponse) Reset()         { *m = MedidorIsActiveResponse{} }
func (m *MedidorIsActiveResponse) String() string { return proto.CompactTextString(m) }
func (*MedidorIsActiveResponse) ProtoMessage()    {}
func (*MedidorIsActiveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_59fab903af14928d, []int{4}
}

func (m *MedidorIsActiveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MedidorIsActiveResponse.Unmarshal(m, b)
}
func (m *MedidorIsActiveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MedidorIsActiveResponse.Marshal(b, m, deterministic)
}
func (m *MedidorIsActiveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MedidorIsActiveResponse.Merge(m, src)
}
func (m *MedidorIsActiveResponse) XXX_Size() int {
	return xxx_messageInfo_MedidorIsActiveResponse.Size(m)
}
func (m *MedidorIsActiveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MedidorIsActiveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MedidorIsActiveResponse proto.InternalMessageInfo

func (m *MedidorIsActiveResponse) GetMedidores() []*MedidorGet {
	if m != nil {
		return m.Medidores
	}
	return nil
}

type MedidorRequest struct {
	MedidorEntry         *Medidor `protobuf:"bytes,1,opt,name=MedidorEntry,proto3" json:"MedidorEntry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MedidorRequest) Reset()         { *m = MedidorRequest{} }
func (m *MedidorRequest) String() string { return proto.CompactTextString(m) }
func (*MedidorRequest) ProtoMessage()    {}
func (*MedidorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59fab903af14928d, []int{5}
}

func (m *MedidorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MedidorRequest.Unmarshal(m, b)
}
func (m *MedidorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MedidorRequest.Marshal(b, m, deterministic)
}
func (m *MedidorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MedidorRequest.Merge(m, src)
}
func (m *MedidorRequest) XXX_Size() int {
	return xxx_messageInfo_MedidorRequest.Size(m)
}
func (m *MedidorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MedidorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MedidorRequest proto.InternalMessageInfo

func (m *MedidorRequest) GetMedidorEntry() *Medidor {
	if m != nil {
		return m.MedidorEntry
	}
	return nil
}

type MedidorCreateResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Result               string   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MedidorCreateResponse) Reset()         { *m = MedidorCreateResponse{} }
func (m *MedidorCreateResponse) String() string { return proto.CompactTextString(m) }
func (*MedidorCreateResponse) ProtoMessage()    {}
func (*MedidorCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_59fab903af14928d, []int{6}
}

func (m *MedidorCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MedidorCreateResponse.Unmarshal(m, b)
}
func (m *MedidorCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MedidorCreateResponse.Marshal(b, m, deterministic)
}
func (m *MedidorCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MedidorCreateResponse.Merge(m, src)
}
func (m *MedidorCreateResponse) XXX_Size() int {
	return xxx_messageInfo_MedidorCreateResponse.Size(m)
}
func (m *MedidorCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MedidorCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MedidorCreateResponse proto.InternalMessageInfo

func (m *MedidorCreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MedidorCreateResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type MedidorResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MedidorResponse) Reset()         { *m = MedidorResponse{} }
func (m *MedidorResponse) String() string { return proto.CompactTextString(m) }
func (*MedidorResponse) ProtoMessage()    {}
func (*MedidorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_59fab903af14928d, []int{7}
}

func (m *MedidorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MedidorResponse.Unmarshal(m, b)
}
func (m *MedidorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MedidorResponse.Marshal(b, m, deterministic)
}
func (m *MedidorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MedidorResponse.Merge(m, src)
}
func (m *MedidorResponse) XXX_Size() int {
	return xxx_messageInfo_MedidorResponse.Size(m)
}
func (m *MedidorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MedidorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MedidorResponse proto.InternalMessageInfo

func (m *MedidorResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type MedidorUUID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MedidorUUID) Reset()         { *m = MedidorUUID{} }
func (m *MedidorUUID) String() string { return proto.CompactTextString(m) }
func (*MedidorUUID) ProtoMessage()    {}
func (*MedidorUUID) Descriptor() ([]byte, []int) {
	return fileDescriptor_59fab903af14928d, []int{8}
}

func (m *MedidorUUID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MedidorUUID.Unmarshal(m, b)
}
func (m *MedidorUUID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MedidorUUID.Marshal(b, m, deterministic)
}
func (m *MedidorUUID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MedidorUUID.Merge(m, src)
}
func (m *MedidorUUID) XXX_Size() int {
	return xxx_messageInfo_MedidorUUID.Size(m)
}
func (m *MedidorUUID) XXX_DiscardUnknown() {
	xxx_messageInfo_MedidorUUID.DiscardUnknown(m)
}

var xxx_messageInfo_MedidorUUID proto.InternalMessageInfo

func (m *MedidorUUID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MedidorMarca struct {
	Marca                string   `protobuf:"bytes,1,opt,name=marca,proto3" json:"marca,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MedidorMarca) Reset()         { *m = MedidorMarca{} }
func (m *MedidorMarca) String() string { return proto.CompactTextString(m) }
func (*MedidorMarca) ProtoMessage()    {}
func (*MedidorMarca) Descriptor() ([]byte, []int) {
	return fileDescriptor_59fab903af14928d, []int{9}
}

func (m *MedidorMarca) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MedidorMarca.Unmarshal(m, b)
}
func (m *MedidorMarca) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MedidorMarca.Marshal(b, m, deterministic)
}
func (m *MedidorMarca) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MedidorMarca.Merge(m, src)
}
func (m *MedidorMarca) XXX_Size() int {
	return xxx_messageInfo_MedidorMarca.Size(m)
}
func (m *MedidorMarca) XXX_DiscardUnknown() {
	xxx_messageInfo_MedidorMarca.DiscardUnknown(m)
}

var xxx_messageInfo_MedidorMarca proto.InternalMessageInfo

func (m *MedidorMarca) GetMarca() string {
	if m != nil {
		return m.Marca
	}
	return ""
}

type MedidorSerial struct {
	Serial               string   `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MedidorSerial) Reset()         { *m = MedidorSerial{} }
func (m *MedidorSerial) String() string { return proto.CompactTextString(m) }
func (*MedidorSerial) ProtoMessage()    {}
func (*MedidorSerial) Descriptor() ([]byte, []int) {
	return fileDescriptor_59fab903af14928d, []int{10}
}

func (m *MedidorSerial) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MedidorSerial.Unmarshal(m, b)
}
func (m *MedidorSerial) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MedidorSerial.Marshal(b, m, deterministic)
}
func (m *MedidorSerial) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MedidorSerial.Merge(m, src)
}
func (m *MedidorSerial) XXX_Size() int {
	return xxx_messageInfo_MedidorSerial.Size(m)
}
func (m *MedidorSerial) XXX_DiscardUnknown() {
	xxx_messageInfo_MedidorSerial.DiscardUnknown(m)
}

var xxx_messageInfo_MedidorSerial proto.InternalMessageInfo

func (m *MedidorSerial) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func init() {
	proto.RegisterType((*Medidor)(nil), "medidorgRPC.Medidor")
	proto.RegisterType((*MedidorGet)(nil), "medidorgRPC.MedidorGet")
	proto.RegisterType((*MedidorUpdate)(nil), "medidorgRPC.MedidorUpdate")
	proto.RegisterType((*MedidorIsActive)(nil), "medidorgRPC.MedidorIsActive")
	proto.RegisterType((*MedidorIsActiveResponse)(nil), "medidorgRPC.MedidorIsActiveResponse")
	proto.RegisterType((*MedidorRequest)(nil), "medidorgRPC.MedidorRequest")
	proto.RegisterType((*MedidorCreateResponse)(nil), "medidorgRPC.MedidorCreateResponse")
	proto.RegisterType((*MedidorResponse)(nil), "medidorgRPC.MedidorResponse")
	proto.RegisterType((*MedidorUUID)(nil), "medidorgRPC.MedidorUUID")
	proto.RegisterType((*MedidorMarca)(nil), "medidorgRPC.MedidorMarca")
	proto.RegisterType((*MedidorSerial)(nil), "medidorgRPC.MedidorSerial")
}

func init() { proto.RegisterFile("medidorgRPC.proto", fileDescriptor_59fab903af14928d) }

var fileDescriptor_59fab903af14928d = []byte{
	// 634 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x4e, 0x13, 0x41,
	0x14, 0x66, 0x4b, 0x5b, 0xe8, 0x29, 0x54, 0x1d, 0x91, 0xae, 0xab, 0x86, 0x66, 0x43, 0xb4, 0x9a,
	0xd8, 0x26, 0x35, 0x26, 0xde, 0x19, 0x0a, 0x4a, 0xaa, 0x21, 0xc2, 0x20, 0x31, 0xd1, 0xab, 0xa1,
	0x7b, 0x24, 0x93, 0x6c, 0x77, 0xeb, 0xcc, 0x40, 0xe2, 0xab, 0xf8, 0x12, 0x3e, 0x82, 0xef, 0xe1,
	0xa3, 0x78, 0x65, 0xd8, 0x99, 0xd9, 0xdd, 0x6e, 0xb7, 0x25, 0xdc, 0xed, 0xf9, 0xfb, 0xfa, 0x9d,
	0xef, 0x3b, 0x1d, 0xb8, 0x37, 0xc1, 0x80, 0x07, 0xb1, 0xb8, 0xa0, 0xc7, 0xfb, 0xbd, 0xa9, 0x88,
	0x55, 0x4c, 0x9a, 0xb9, 0x94, 0xb7, 0x73, 0x11, 0xc7, 0x17, 0x21, 0xf6, 0x93, 0xd2, 0xf9, 0xe5,
	0xf7, 0xbe, 0xe2, 0x13, 0x94, 0x8a, 0x4d, 0xa6, 0xba, 0xdb, 0x6b, 0x5f, 0xb1, 0x90, 0x07, 0x4c,
	0x61, 0xdf, 0x7e, 0xe8, 0x82, 0xff, 0xab, 0x02, 0x6b, 0x47, 0x1a, 0x89, 0x6c, 0x41, 0xed, 0x5c,
	0xb0, 0x28, 0x70, 0x9d, 0x8e, 0xd3, 0x6d, 0x50, 0x1d, 0x10, 0x17, 0xd6, 0x58, 0x10, 0x08, 0x94,
	0xd2, 0xad, 0x24, 0x79, 0x1b, 0x92, 0xf7, 0x70, 0x97, 0x47, 0x52, 0xb1, 0x30, 0x64, 0x8a, 0xc7,
	0xd1, 0x01, 0x53, 0xe8, 0xae, 0x76, 0x9c, 0x6e, 0x73, 0xe0, 0xf5, 0x34, 0xa1, 0x9e, 0x25, 0xd4,
	0xfb, 0x6c, 0x09, 0xd1, 0xb9, 0x19, 0x32, 0x84, 0x96, 0x40, 0xc5, 0x05, 0x4e, 0x30, 0x52, 0x09,
	0x4a, 0xf5, 0x46, 0x94, 0xc2, 0x04, 0xd9, 0x86, 0xba, 0x44, 0xc1, 0x59, 0xe8, 0xd6, 0x12, 0x92,
	0x26, 0x22, 0x3b, 0x50, 0x0b, 0x79, 0x84, 0xd2, 0xad, 0x77, 0x9c, 0x6e, 0x75, 0xd8, 0xf8, 0x37,
	0xac, 0x0f, 0xaa, 0x2e, 0x74, 0x1d, 0xaa, 0xf3, 0xc4, 0x83, 0x75, 0x2e, 0xf7, 0xc6, 0x8a, 0x5f,
	0xa1, 0xbb, 0xd6, 0x71, 0xba, 0xeb, 0x34, 0x8d, 0xfd, 0xbf, 0x0e, 0x80, 0x11, 0xe7, 0x10, 0xd5,
	0xad, 0xf5, 0x79, 0x31, 0xab, 0x4f, 0x60, 0xf5, 0x69, 0xd0, 0xb9, 0x3c, 0x79, 0x9a, 0xd7, 0x20,
	0xb0, 0x1a, 0x34, 0x68, 0x21, 0xbb, 0x70, 0xcf, 0xad, 0xfc, 0x9e, 0xb5, 0x99, 0xe5, 0x58, 0x61,
	0x39, 0x1d, 0xfb, 0xbf, 0x1d, 0xd8, 0x34, 0xcb, 0x9d, 0x4d, 0x13, 0xec, 0x16, 0x54, 0xb8, 0x5d,
	0xae, 0xc2, 0x97, 0x6d, 0x36, 0xef, 0xd8, 0xea, 0xad, 0x1d, 0x4b, 0x19, 0x57, 0xe7, 0x18, 0x1b,
	0x3b, 0x6a, 0x05, 0x3b, 0x5e, 0xc2, 0x1d, 0x43, 0x78, 0x64, 0x52, 0x33, 0xed, 0x4e, 0xa1, 0xfd,
	0x18, 0xda, 0x85, 0x76, 0x8a, 0x72, 0x1a, 0x47, 0x12, 0xc9, 0x6b, 0x68, 0x98, 0x12, 0x4a, 0xd7,
	0xe9, 0xac, 0x76, 0x9b, 0x83, 0x76, 0x2f, 0xff, 0x1f, 0xcb, 0x5c, 0xa7, 0x59, 0xa7, 0xff, 0x01,
	0x5a, 0x26, 0xa0, 0xf8, 0xe3, 0x12, 0xa5, 0x22, 0x6f, 0x60, 0xc3, 0x64, 0xde, 0x45, 0x4a, 0xfc,
	0x4c, 0x38, 0x34, 0x07, 0x5b, 0x65, 0x58, 0x74, 0xa6, 0xd3, 0x7f, 0x0b, 0x0f, 0x4c, 0xbc, 0x2f,
	0x90, 0xa9, 0x8c, 0x5b, 0xd1, 0x85, 0x6d, 0xa8, 0x0b, 0x94, 0x97, 0xa1, 0x32, 0x26, 0x98, 0xc8,
	0x7f, 0x9e, 0xaa, 0x91, 0x8e, 0x66, 0xad, 0xce, 0x4c, 0xeb, 0x13, 0x68, 0x5a, 0xa7, 0xcf, 0x46,
	0x07, 0xc5, 0x5f, 0xf0, 0x77, 0xd3, 0x25, 0x8e, 0x98, 0x18, 0xb3, 0x6b, 0x67, 0x26, 0xd7, 0x1f,
	0xf6, 0xce, 0x93, 0xc0, 0x7f, 0x96, 0x9e, 0xcb, 0xa9, 0x3e, 0xb9, 0xec, 0x14, 0x9d, 0xfc, 0x29,
	0x0e, 0xfe, 0x54, 0x53, 0x99, 0x4e, 0x51, 0x5c, 0xf1, 0x31, 0x92, 0x13, 0xd8, 0xf8, 0x22, 0xb8,
	0x42, 0xfb, 0xd2, 0x3c, 0x2a, 0x15, 0x48, 0x6b, 0xea, 0xf9, 0x65, 0xc5, 0x59, 0x91, 0xfc, 0x15,
	0xb2, 0x07, 0x70, 0x88, 0xca, 0x02, 0xba, 0x65, 0x33, 0xd7, 0xcb, 0x7a, 0x8b, 0x7c, 0xf5, 0x57,
	0xc8, 0x47, 0xd8, 0xd4, 0x97, 0x6f, 0x51, 0xbc, 0x52, 0x94, 0xa4, 0xc5, 0x7b, 0x5c, 0x4e, 0x39,
	0xe5, 0x33, 0x82, 0xcd, 0x03, 0x0c, 0x31, 0x03, 0x5b, 0x4c, 0xe9, 0x26, 0xa8, 0x6f, 0x70, 0x3f,
	0x5b, 0x6d, 0xa4, 0x5f, 0x0a, 0x0c, 0x48, 0xe9, 0x98, 0x3d, 0x6d, 0x6f, 0x77, 0x59, 0x35, 0x07,
	0xfe, 0x09, 0xda, 0x14, 0xc7, 0x18, 0xa9, 0x51, 0xee, 0x09, 0xd2, 0xbe, 0x3f, 0x2c, 0x83, 0x48,
	0x4a, 0xcb, 0x54, 0x3c, 0x01, 0x77, 0x1e, 0xd0, 0x9c, 0x48, 0xa9, 0xa0, 0xba, 0xb6, 0x04, 0x72,
	0xd8, 0xfa, 0xba, 0xd1, 0xcf, 0x15, 0xcf, 0xeb, 0xc9, 0x73, 0xf2, 0xea, 0x7f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x9c, 0x01, 0x7a, 0x0a, 0x07, 0x07, 0x00, 0x00,
}
